version: "3.5"
services:
  app:
    container_name: card-service
    build:
      context: ../
      dockerfile: ./development/Dockerfile
    ports:
      - 80:80
    volumes:
      - ../:/home/app
    #networks:
      #- app_network

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: creditcard

    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  postgres-db:

#networks:
  #app_network:
    #driver: bridge
